CREATE SEQUENCE IF NOT EXISTS scan_results_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS findings_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS code_embeddings_seq START WITH 1 INCREMENT BY 50;